<?php
if ($_SERVER['PHP_AUTH_USER'] == "eji") {
		$host = "feetster.dyndns.org";
		$port = "4337";
		$export = "6969";
		$mount = "feet.ts";
}
if ($_SERVER['PHP_AUTH_USER'] == "poker") {
		$host = "70.119.55.101";
		$port = "8676";
		$export = "4545";
		$mount = "poker.ts";
}
if ($_SERVER['PHP_AUTH_USER'] == "rface") {
		$host = "68.101.116.74";
		$port = "9988";
		$export = "9988";
		$mount = "tv.ts";
}
if ($_SERVER['PHP_AUTH_USER'] == "momo") {
		$host = "momotombo.ath.cx";
		$port = "6464";
		$export = "6464";
		$mount = "momo.ts";
}
if ($_SERVER['PHP_AUTH_USER'] == "narunetto") {
		$host = "minchi.imcumm.in";
		$port = "6969";
		$export = "4578";
		$mount = "narunetto.ts";
}
if ($_SERVER['PHP_AUTH_USER'] == "kyat") {
		$host = "N/A";
		$port = "1101";
		$export = "1101";
		$mount = "kyat.ts";
}
if ($_SERVER['PHP_AUTH_USER'] == "luis") {
		$host = "N/A";
		$port = "7777";
		$export = "7777";
		$mount = "luis.ts";
}
if ($_SERVER['PHP_AUTH_USER'] == "rofl") {
		$host = "24.49.57.145";
		$port = "7707";
		$export = "7707";
		$mount = "rofl.ts";
}
?>
